name: calculator_flutter
description: >-
  An example Flutter application.
version: 1.0.0
homepage: https://github.com/sanket-kankariya/Calculator-flutter

environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
